/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.livescore.view;

import com.livescore.model.Match;
import com.livescore.model.MatchData;
import com.livescore.util.ValidationUtil;
import javax.swing.JOptionPane;
import java.util.*;

/**
 *
 * @author Lenovo
 */
public class Addmatch extends javax.swing.JFrame {
    
    
    // Static list to store all match data
    public static List<Match> matches = new ArrayList<>();
    /**
     * Creates new form Addmatch
     */
    public Addmatch() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        team2_name = new javax.swing.JTextField();
        team1_score = new javax.swing.JTextField();
        team1_name = new javax.swing.JTextField();
        ven = new javax.swing.JTextField();
        AddSubmit = new javax.swing.JButton();
        AddBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        team2_score = new javax.swing.JTextField();
        sta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("ADD MATCH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 184, 59));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Match Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 76, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Team 1 name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 104, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Team 2 name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 104, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Team 1 score");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Venue");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 70, -1));

        mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midActionPerformed(evt);
            }
        });
        getContentPane().add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 170, -1));

        team2_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team2_nameActionPerformed(evt);
            }
        });
        getContentPane().add(team2_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 170, -1));

        team1_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team1_scoreActionPerformed(evt);
            }
        });
        getContentPane().add(team1_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 170, -1));

        team1_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team1_nameActionPerformed(evt);
            }
        });
        getContentPane().add(team1_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 170, -1));

        ven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venActionPerformed(evt);
            }
        });
        getContentPane().add(ven, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 170, -1));

        AddSubmit.setBackground(new java.awt.Color(13, 103, 137));
        AddSubmit.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        AddSubmit.setForeground(new java.awt.Color(255, 255, 255));
        AddSubmit.setText("Submit");
        AddSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(AddSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, -1, -1));

        AddBack.setBackground(new java.awt.Color(0, 102, 102));
        AddBack.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        AddBack.setForeground(new java.awt.Color(255, 255, 255));
        AddBack.setText("Back");
        AddBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBackActionPerformed(evt);
            }
        });
        getContentPane().add(AddBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 80, -1));

        team2_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team2_scoreActionPerformed(evt);
            }
        });
        getContentPane().add(team2_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 170, -1));

        sta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staActionPerformed(evt);
            }
        });
        getContentPane().add(sta, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 170, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Team 2 score");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/livescore/resources/add (1).jpeg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -160, 1650, 1050));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midActionPerformed

    private void team2_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team2_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_team2_nameActionPerformed

    private void team1_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team1_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_team1_scoreActionPerformed

    private void team1_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team1_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_team1_nameActionPerformed

    private void venActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venActionPerformed

    private void AddBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBackActionPerformed

        new homepage().setVisible(true);
    }//GEN-LAST:event_AddBackActionPerformed

    private void AddSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSubmitActionPerformed
                                                                                 
    // Retrieve input values
    String matchId = mid.getText();
    String team1 = team1_name.getText();
    String team1Score = team1_score.getText();
    String team2 = team2_name.getText();
    String team2Score = team2_score.getText();
    String status = sta.getText();
    String venue = ven.getText(); 

    // Validate the input using ValidationUtil methods
        if (ValidationUtil.isEmpty(matchId) || ValidationUtil.isEmpty(team1) || 
            ValidationUtil.isEmpty(team1Score) || ValidationUtil.isEmpty(team2) || 
            ValidationUtil.isEmpty(team2Score)) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate matchId to be numeric
        if (!ValidationUtil.isNumeric(matchId)) {
            JOptionPane.showMessageDialog(this, "Match ID should be numeric.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate that team names do not contain numbers
        if (ValidationUtil.containsNumbers(team1)) {
            JOptionPane.showMessageDialog(this, "Team 1 name contains numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (ValidationUtil.containsNumbers(team2)) {
            JOptionPane.showMessageDialog(this, "Team 2 name contains numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if the matchId already exists
        if (MatchData.getMatchById(matchId) != null) {
            JOptionPane.showMessageDialog(this, "Match ID already exists. Please enter a unique Match ID.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Convert team scores to integers
            int team1ScoreInt = Integer.parseInt(team1Score);
            int team2ScoreInt = Integer.parseInt(team2Score);

            // Validate scores
            if (!ValidationUtil.areScoresValid(team1ScoreInt, team2ScoreInt)) {
                JOptionPane.showMessageDialog(this, "Scores cannot be negative.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Create a new Match object and add it to the list
            Match newMatch = new Match(matchId, team1, team1ScoreInt, team2, team2ScoreInt, status, venue);
            MatchData.addMatch(newMatch);

            JOptionPane.showMessageDialog(this, "Match Added Successfully!");

            // Clear input fields
            mid.setText("");
            team1_name.setText("");
            team1_score.setText("");
            team2_name.setText("");
            team2_score.setText("");
            sta.setText("");
            ven.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid scores as integers.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_AddSubmitActionPerformed

    private void team2_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team2_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_team2_scoreActionPerformed

    private void staActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addmatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addmatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addmatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addmatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addmatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBack;
    private javax.swing.JButton AddSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField sta;
    private javax.swing.JTextField team1_name;
    private javax.swing.JTextField team1_score;
    private javax.swing.JTextField team2_name;
    private javax.swing.JTextField team2_score;
    private javax.swing.JTextField ven;
    // End of variables declaration//GEN-END:variables
}
